### ISSUE TITLE
Cache decompiled sources

### ISSUE THREAD

**Issue by fbricon** [dgileadi/dg.jdt.ls.decompiler#2]
jdt.ls' ContentProviderManager no longer manages a global cache of decompiled content. It's now each IContentProvider implementation's responsibility for caching their results  (See https://github.com/eclipse/eclipse.jdt.ls/pull/562). 
Fernflower and Procyon are rather slow to decompile sources so they will be most impacted by that change

**Comment by dgileadi** [comment]
Added caching.
