### ISSUE TITLE
Updated build

### ISSUE THREAD

**Issue by jaghaimo** [dgileadi/dg.jdt.ls.decompiler#3]
As far as I am aware, this is the only decompiler plugin for `eclipse.jdt.ls`. Unfortunately the last build is from 2018, and in the meantime multiple newer releases of bundled decompilers has been released (25 releases of CFR, multiples of Fernflower, and Procyon seems to be abandoned). Would it be possible to update this repository, so that it once again possible to build (and update bundled decompilers)? 

With these changes I was able to build working plugins: https://github.com/dgileadi/dg.jdt.ls.decompiler/compare/master...jaghaimo-forks:master

I was also able to replace `fernflower.jar` with one build today, rebuild, and still successfully use in (after swapping jars in your vscode plugin). Unfortunately CFR will require a bit more work as the API changed a lot (other fork of your repo managed to get update to 146).

**Comment by dgileadi** [comment]
I hugely appreciate this work! If you're willing to make a pull request I'll gladly accept your changes.

I'd be pleased if someone more official than I would take over this plugin; as you've noticed I've been letting it languish. But in the mean time I'm very grateful for your work on it.

**Comment by jaghaimo** [comment]
> I hugely appreciate this work! If you're willing to make a pull request I'll gladly accept your changes.

Done. I've just included minimal changes I made to make this project buildable. You may want to enable Github Actions (Build with Maven) to have verified that each (future) commit is buildable.

**Comment by jaghaimo** [comment]
> I'd be pleased if someone more official than I would take over this plugin; as you've noticed I've been letting it languish. But in the mean time I'm very grateful for your work on it.

I assume this would be a good project to pull under eclipse.jdt.ls umbrella. A requirement would be probably to stop bundling 3rd party libraries (which should be doable, on Maven Central you can find official CFR (https://mvnrepository.com/artifact/org.benf/cfr) as well as unofficial (Windup by Redhat) fernflower and procyon https://mvnrepository.com/artifact/org.jboss.windup.decompiler).

**Comment by jaghaimo** [comment]
Closed as of https://github.com/dgileadi/dg.jdt.ls.decompiler/pull/4
